### YamlMime:QSharpNamespace
functions: []
name: Microsoft.Quantum.Environment
newtypes: []
operations:
- summary: Şu anda ödünç alma için kullanılabilen qubits sayısını döndürür. Buna kullanılmayan qubits dahildir; diğer bir deyişle, tarafından döndürülen qubits 'i de içerir `GetQubitsAvailableToUse` .
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToBorrow
- summary: Şu anda kullanılabilecek qubits sayısını döndürür.
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToUse
summary: Bu işlevler, hisse içindeki hisse hesaplamasının oluşturulduğu ortam hakkında bilgiler sağlar.
uid: Microsoft.Quantum.Environment
metadata:
  ms.openlocfilehash: 04a3ffe56be7da2c9adc13e2b27fe9ce0f982c44
  ms.sourcegitcommit: 29e0d88a30e4166fa580132124b0eb57e1f0e986
  ms.translationtype: MT
  ms.contentlocale: tr-TR
  ms.lasthandoff: 10/27/2020
  ms.locfileid: "92727421"
