### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletoborrow
name: GetQubitsAvailableToBorrow
type: operation
namespace: microsoft.quantum.environment
summary: >-
  Şu anda ödünç alma için kullanılabilen qubits sayısını döndürür.

  Buna kullanılmayan qubits dahildir; diğer bir deyişle, tarafından döndürülen qubits 'i de içerir `GetQubitsAvailableToUse` .
syntax: 'operation GetQubitsAvailableToBorrow () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      Bir bildirimde ayrılabilen qubit sayısı `borrowing` .

      Kullanılan hedef makine bu bilgileri sağlamıyorsa, `-1` döndürülür.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletouse
metadata:
  ms.openlocfilehash: 18e68548e9f344a70dac95f70528a8b3e87f5909
  ms.sourcegitcommit: 685a8ab16d7e6a25e63a168d6e7c385fa6e876cc
  ms.translationtype: MT
  ms.contentlocale: tr-TR
  ms.lasthandoff: 09/29/2020
  ms.locfileid: "91478078"
