### YamlMime:QSharpNamespace
uid: microsoft.quantum.environment
name: Microsoft.Quantum.Environment
summary: " # <a name=\"summary\"></a>Özet\n Bu işlevler, hisse içindeki hisse hesaplamasının oluşturulduğu ortam hakkında bilgiler sağlar."
operations:
- uid: microsoft.quantum.environment.getqubitsavailabletoborrow
  summary: >-
    Şu anda ödünç alma için kullanılabilen qubits sayısını döndürür.

    Buna kullanılmayan qubits dahildir; diğer bir deyişle, `GetQubitsAvailableToUse`tarafından döndürülen qubits 'i de içerir.
- uid: microsoft.quantum.environment.getqubitsavailabletouse
  summary: Şu anda kullanılabilecek qubits sayısını döndürür.
metadata:
  ms.openlocfilehash: 50e5cfb7c1b9a4075c25b2705d00b435a09e159e
  ms.sourcegitcommit: edcf15044d7bdf4f8b21fb8f6af4bde475eb13a0
  ms.translationtype: MT
  ms.contentlocale: tr-TR
  ms.lasthandoff: 11/05/2019
  ms.locfileid: "73056823"
