### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletouse
name: GetQubitsAvailableToUse
type: operation
namespace: Microsoft.Quantum.Environment
summary: Şu anda kullanılabilecek qubits sayısını döndürür.
syntax: 'operation GetQubitsAvailableToUse () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      Bir `using` bildirimde ayrılabilen qubit sayısı.

      Kullanılan hedef makine bu bilgileri sağlamıyorsa, `-1` döndürülür.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletoborrow
metadata:
  ms.openlocfilehash: 82d8c27064cbb234b32707aa31fb0869f66ce23c
  ms.sourcegitcommit: db23885adb7ff76cbf8bd1160d401a4f0471e549
  ms.translationtype: MT
  ms.contentlocale: tr-TR
  ms.lasthandoff: 05/01/2020
  ms.locfileid: "82682391"
