### YamlMime:QSharpNamespace
uid: microsoft.quantum.environment
name: Microsoft.Quantum.Environment
summary: " # <a name=\"summary\"></a>Özet\n Bu işlevler, hisse içindeki hisse hesaplamasının oluşturulduğu ortam hakkında bilgiler sağlar."
operations:
- uid: microsoft.quantum.environment.getqubitsavailabletoborrow
  summary: >-
    Şu anda ödünç alma için kullanılabilen qubits sayısını döndürür.

    Buna kullanılmayan qubits dahildir; diğer bir deyişle, tarafından `GetQubitsAvailableToUse`döndürülen qubits 'i de içerir.
- uid: microsoft.quantum.environment.getqubitsavailabletouse
  summary: Şu anda kullanılabilecek qubits sayısını döndürür.
metadata:
  ms.openlocfilehash: bd6d442aabb179f4c5fea0a0f48efaa472ec00cf
  ms.sourcegitcommit: db23885adb7ff76cbf8bd1160d401a4f0471e549
  ms.translationtype: MT
  ms.contentlocale: tr-TR
  ms.lasthandoff: 05/01/2020
  ms.locfileid: "82673342"
